on: push
name: Text Lint
jobs:
  remark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
      - name: Install
        run: npm install
      - name: Test
        run: textlint *.md _posts/*.md _resume_positions/*.md
